#!/usr/bin/bash

dir="$HOME/.config/rofi/power.rasi"

shutdown=" Shutdown"
reboot=" Reboot"
suspend=" Suspend"
lock=" Lock"
logout=" Logout"

option=$(echo -e "$shutdown\n$reboot\n$logout\n$lock\n$suspend" | rofi -dmenu -theme "$dir" -lines 5)

case "$option" in
    "$shutdown")
        systemctl poweroff
        ;;
    "$reboot")
        systemctl reboot
        ;;
    "$suspend")
        systemctl suspend
        ;;
    "$lock")
        # TODO: add lock behavior, betterlockscreen?
        ;;
    "$logout")
        hyprctl dispatch exit
        ;;
esac
