#!/usr/bin/python

import subprocess
import time

if __name__ == "__main__":
    o = subprocess.run(["ps", "cax"], capture_output=True)

    # Show the bar
    # We want to replace because it'll show this process in the output
    if b"waybar" in (o.stdout.replace(b"toggle_waybar", b"")):
        subprocess.Popen(["killall", "waybar"])
        for gap in range(10, 0, -1):
            subprocess.Popen(
                ["hyprctl", f"keyword general:gaps_out {gap}"]).wait()
            time.sleep(0.1)
    # Hide the bar
    else:
        subprocess.Popen(["waybar"])
        # Kinda animate adding the gaps
        for gap in range(1, 11):
            subprocess.Popen(
                ["hyprctl", f"keyword general:gaps_out {gap}"]).wait()
            time.sleep(0.1)
